# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanoproxy < Formula
  desc "Simple Socks5 Proxy written in Go"
  homepage "https://github.com/ryanbekhen/nanoproxy"
  version "0.12.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.12.3/nanoproxy_Darwin_arm64.tar.gz"
      sha256 "70dc65d442f1512b08d44003b096ab4469190d8f346369b4174075caf668d675"

      def install
        bin.install "nanoproxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.12.3/nanoproxy_Darwin_x86_64.tar.gz"
      sha256 "a9392bcf2814ce16208560daebd7b883a5c7a303fb6582f73e8c801617c5cb1d"

      def install
        bin.install "nanoproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.12.3/nanoproxy_Linux_arm64.tar.gz"
      sha256 "70cebd9ca08fea3fb2057c34b48e91409047df0c18a3494a3da81ea662923b8e"

      def install
        bin.install "nanoproxy"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.12.3/nanoproxy_Linux_armv7.tar.gz"
      sha256 "031ddd6c5ce5691b751eb6dcb55a20cb857146e5df51782837144b5c0b9a7539"

      def install
        bin.install "nanoproxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.12.3/nanoproxy_Linux_x86_64.tar.gz"
      sha256 "746a758b9f388b37598ac9f00007e319bba95bd9e0f984deaecdf6957af61786"

      def install
        bin.install "nanoproxy"
      end
    end
  end
end
