# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanoproxy < Formula
  desc "NanoProxy is a simple reverse proxy written in Go."
  homepage "https://github.com/ryanbekhen/nanoproxy"
  version "0.12.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.12.2/nanoproxy_Darwin_arm64.tar.gz"
      sha256 "32d46ced7939a97934fb3734121180c2909e20f444dd554ff713a741143963c0"

      def install
        bin.install "nanoproxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.12.2/nanoproxy_Darwin_x86_64.tar.gz"
      sha256 "1b96eb0ac0958424625f68864ec8cf78c93ffcc4c8453ab432396b8c8f5adb06"

      def install
        bin.install "nanoproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.12.2/nanoproxy_Linux_arm64.tar.gz"
      sha256 "c7502bce67fe4bd94e22622fe041825cf86e2a369e775ae0fd8e4ef56eea6e92"

      def install
        bin.install "nanoproxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.12.2/nanoproxy_Linux_x86_64.tar.gz"
      sha256 "a63aaf3b254b7b073651b0fed2da9f92955de57a839978b80f801c8be501f700"

      def install
        bin.install "nanoproxy"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.12.2/nanoproxy_Linux_armv7.tar.gz"
      sha256 "b589784b9f0d4765014672ff10adc52cb84af774f501803f49b4ae61d2786215"

      def install
        bin.install "nanoproxy"
      end
    end
  end
end
