# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nanoproxy < Formula
  desc "nanoproxy is a simple reverse proxy written in Go."
  homepage "https://github.com/ryanbekhen/nanoproxy"
  version "0.12.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.12.1/nanoproxy_Darwin_x86_64.tar.gz"
      sha256 "e47a06a692583b79b49979d493a5fcfd5c5bf2445fd43e100b7c3ba8ea82bef4"

      def install
        bin.install "nanoproxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.12.1/nanoproxy_Darwin_arm64.tar.gz"
      sha256 "941b08d991e4651718eff56c85ad2dbde6a7faffdb99a50504ca027ec0d9df05"

      def install
        bin.install "nanoproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.12.1/nanoproxy_Linux_armv7.tar.gz"
      sha256 "06a0028de2bb7de588d2e58a1d94c02474ede9b204770e0dcf6a3e67de8f26a4"

      def install
        bin.install "nanoproxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.12.1/nanoproxy_Linux_x86_64.tar.gz"
      sha256 "fdcadb628df8ab3b7e1a4673e4ec21095d7f8bdb10d2334ef9f7f83341ffce1c"

      def install
        bin.install "nanoproxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ryanbekhen/nanoproxy/releases/download/v0.12.1/nanoproxy_Linux_arm64.tar.gz"
      sha256 "d34d0dcb93c545a515f50b35681fd9bc30eb7c6ab8fe93742fc5ba595d533a85"

      def install
        bin.install "nanoproxy"
      end
    end
  end
end
