# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Regit < Formula
  desc "CLI tool to manage git repositories and histories"
  homepage "https://github.com/woaitsAryan/regit"
  version "0.2.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/woaitsAryan/regit/releases/download/v0.2.11/regit_MacOS_x86_64.tar.gz"
      sha256 "cbbaafeb5e60dd9a6e9773174e9c34f43074c08811bcc63f1dd79a463ce545fd"

      def install
        bin.install "regit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/woaitsAryan/regit/releases/download/v0.2.11/regit_MacOS_arm64.tar.gz"
      sha256 "07b04ad1a80a1c64c36bdf52fcdda0b7ebe90d6ca9495d52260d4903d9a227ca"

      def install
        bin.install "regit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/woaitsAryan/regit/releases/download/v0.2.11/regit_Linux_x86_64.tar.gz"
      sha256 "21282f0cb333f5cf26d4cbcc9a0fb4ecd67cebf91361a0de6aaa8f3f62c48210"

      def install
        bin.install "regit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/woaitsAryan/regit/releases/download/v0.2.11/regit_Linux_arm64.tar.gz"
      sha256 "69ff1ceda63294d8d3a9f19cc73eac3525c300dae8a572d23845fc516345ff48"

      def install
        bin.install "regit"
      end
    end
  end

  def caveats
    <<~EOS
      Just run the command by typing regit, the help menu will assist you
    EOS
  end

  test do
    system "#{bin}/regit", "help"
  end
end
