# This file was generated by GoReleaser. DO NOT EDIT.
class AgentBrowser < Formula
  desc "Browser for agents"
  homepage "https://github.com/co-browser/browser-use-mcp-server"
  version "1.3.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://storage.googleapis.com/cobrowser-images/agent-browser-v1.3.2-darwin-amd64.tar.gz"
      sha256 "1ae6bb3c2201f944c82f6c2f0e3c2a1e6264e511b022969d2568f7c34358f5a0"

      def install
        bin.install "agent-browser"
      end
    end
    on_arm do
      url "https://storage.googleapis.com/cobrowser-images/agent-browser-v1.3.2-darwin-arm64.tar.gz"
      sha256 "198dddbcd5c5ea2f00bc4e5ed59a1d20a8d073526fa1b15b1161aef3d743485c"

      def install
        bin.install "agent-browser"
      end
    end
  end

  on_linux do
    on_intel do
      url "https://storage.googleapis.com/cobrowser-images/agent-browser-v1.3.2-linux-amd64.tar.gz"
      sha256 "9aa9f8a19a68df141c135b7c2024e085faddf2395ab3336d6bb4292a78454d95"

      def install
        bin.install "agent-browser"
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://storage.googleapis.com/cobrowser-images/agent-browser-v1.3.2-linux-arm64.tar.gz"
        sha256 "f7d38f25cd858557c934f108e55f78dacbffbb1af9b84c78102929945d64d766"
        def install
          bin.install "agent-browser"
        end
      end
    end
  end

  test do
    shell_script = <<~EOS
      bin/agent-browser &
      pid=$!
      sleep 1
      if ps -p $pid > /dev/null; then
          kill $pid
          echo "Success: agent-browser started and was killed."
      else
          wait $pid
          status=$?
          echo "Error: agent-browser failed to start or exited immediately with status $status."
      fi
    EOS
    system shell_script
  end
end
