# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitkrakenCli < Formula
  desc "gk is GitKraken on the command line.
It makes working across multiple repos easier with Workspaces, provides access to pull requests and issues from multiple services (GitHub, GitLab, Bitbucket, etc.), and seamlessly connects with GitKraken Client and GitLens in VS Code to visualize git information when you need it."
  homepage "https://www.gitkraken.com/"
  version "3.0.1"
  license "CC-BY-3.0-US"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gitkraken/gk-cli/releases/download/v3.0.1/gk_3.0.1_darwin_amd64.zip", using: CurlDownloadStrategy
      sha256 "cf3df384f1d6875a5bbe599bd3367b9ce07e26b2053e92605b306afdaa63b1f2"

      def install
        bin.install "gk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gitkraken/gk-cli/releases/download/v3.0.1/gk_3.0.1_darwin_arm64.zip", using: CurlDownloadStrategy
      sha256 "ef0a9f91f6629ea8511862e83ac2a0bf4689699e358f21843941c81326539438"

      def install
        bin.install "gk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gitkraken/gk-cli/releases/download/v3.0.1/gk_3.0.1_linux_amd64.zip", using: CurlDownloadStrategy
        sha256 "0bdaf5985b2aec3d9b8d3ff2424d740284f6cf9758556f760e5460dd280635bf"

        def install
          bin.install "gk"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gitkraken/gk-cli/releases/download/v3.0.1/gk_3.0.1_linux_arm64.zip", using: CurlDownloadStrategy
        sha256 "579e5f5ecb121ee7b1c3ff14879cb447220b3871d3b541e585dc760945c28a7c"

        def install
          bin.install "gk"
        end
      end
    end
  end
end
