# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Regit < Formula
  desc "regit is a CLI tool written in Golang with several features to manage git repositories and histories."
  homepage "https://github.com/woaitsAryan/regit"
  version "0.2.8"
  license "MIT"

  on_macos do
    url "https://github.com/woaitsAryan/regit/releases/download/v0.2.8/regit_MacOS_all.tar.gz", using: CurlDownloadStrategy,
      headers: [
          "Accept: application/octet-stream"
      ]
    sha256 "a5b7d8406727bddee96fc467eafd7e38e78917f48a0da6cbef10d419c47751bf"

    def install
      bin.install "regit"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/woaitsAryan/regit/releases/download/v0.2.8/regit_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
            "Accept: application/octet-stream"
        ]
      sha256 "5c176e48f0080a801a10655c707c941949b09a8a246af3522e66cfbcac2fc13c"

      def install
        bin.install "regit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/woaitsAryan/regit/releases/download/v0.2.8/regit_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
            "Accept: application/octet-stream"
        ]
      sha256 "afbecb365ddc72ff391c3e8a23900073e7891fcb5fdcea3ee8ea87c557dea369"

      def install
        bin.install "regit"
      end
    end
  end

  def caveats
    <<~EOS
      Just run the command by typing regit, the help menu will assist you
    EOS
  end

  test do
    system "#{bin}/regit help"
  end
end
