class Lib3mf < Formula
  desc "Implementation of the 3D Manufacturing Format file standard"
  homepage "https://3mf.io"
  url "https://github.com/3MFConsortium/lib3mf/archive/refs/tags/v2.4.1.tar.gz"
  sha256 "081dea66ddd1b958644bfac0fe9a580e63726061459efce5190a10161082f8f7"
  license "BSD-2-Clause"

  depends_on "cmake" => :build
  depends_on "pkgconf" => [:build, :test]
  depends_on "libzip"
  depends_on "openssl@3"
  uses_from_macos "zlib"

  on_linux do
    depends_on "zlib-ng-compat"
  end

  patch :DATA

  def install
    args = %w[
      -DCMAKE_POLICY_VERSION_MINIMUM=3.5
      -DUSE_INCLUDED_ZLIB=OFF
      -DUSE_INCLUDED_LIBZIP=OFF
      -DUSE_INCLUDED_SSL=OFF
      -DLIB3MF_TESTS=OFF
    ]

    system "cmake", "-S", ".", "-B", "build", *args, *std_cmake_args
    system "cmake", "--build", "build"
    system "cmake", "--install", "build"
  end

  test do
    (testpath/"test.c").write <<~C
      #include <lib3mf.h>
      int main() { return 0; }
    C

    pkg_config_cflags = shell_output("pkg-config --cflags --libs lib3mf").chomp.split
    system ENV.cc, "test.c", *pkg_config_cflags, "-o", "test"
    system "./test"
  end
end

__END__
diff --git a/CMakeLists.txt b/CMakeLists.txt
index c6a31790..b5ab7454 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -6,8 +6,6 @@ cmake_policy(SET CMP0048 NEW)
 
 set_property(GLOBAL PROPERTY USE_FOLDERS ON)
 
-include(GNUInstallDirs)
-
 # Define Version
 set(LIB3MF_VERSION_MAJOR 2)        # increase on every backward-compatibility breaking change of the API
 set(LIB3MF_VERSION_MINOR 4)        # increase on every backward compatible change of the API
@@ -18,15 +16,23 @@ project(lib3mf
   VERSION ${LIB3MF_VERSION_MAJOR}.${LIB3MF_VERSION_MINOR}.${LIB3MF_VERSION_MICRO}
   DESCRIPTION "An implementation of the 3D Manufacturing Format file standard"
 )
+include(GNUInstallDirs)
 
 find_program(buildcache_program buildcache)
 if(buildcache_program)
   set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE "${buildcache_program}")
 endif()
 
-set(CMAKE_INSTALL_BINDIR bin CACHE PATH "directory for installing binary files")
-set(CMAKE_INSTALL_LIBDIR lib CACHE PATH "directory for installing library files")
-set(CMAKE_INSTALL_INCLUDEDIR include/lib3mf CACHE PATH "directory for installing header files")
+# Use GNUInstallDirs defaults unless explicitly overridden by the caller.
+if(CMAKE_INSTALL_BINDIR_INITIALIZED_TO_DEFAULT)
+  set(CMAKE_INSTALL_BINDIR "bin" CACHE PATH "directory for installing binary files" FORCE)
+endif()
+if(CMAKE_INSTALL_LIBDIR_INITIALIZED_TO_DEFAULT)
+  set(CMAKE_INSTALL_LIBDIR "lib" CACHE PATH "directory for installing library files" FORCE)
+endif()
+if(CMAKE_INSTALL_INCLUDEDIR STREQUAL "include")
+  set(CMAKE_INSTALL_INCLUDEDIR "include/lib3mf" CACHE PATH "directory for installing header files" FORCE)
+endif()
 
 option(USE_INCLUDED_ZLIB "Use included zlib" ON)
 option(USE_INCLUDED_LIBZIP "Use included libzip" ON)
@@ -127,6 +133,13 @@ add_library(${PROJECT_NAME} SHARED ${SRCS_COMMON} ${HDRS_COMMON}
   ${ACT_GENERATED_SOURCE}
   ${VERSION_FILES_OUTPUTLOCATION}
 )
+add_custom_command(TARGET ${PROJECT_NAME} POST_BUILD
+  COMMAND
+    ${CMAKE_COMMAND}
+    -DTARGET_FILE=$<TARGET_FILE:${PROJECT_NAME}>
+    -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/VerifyTargetFile.cmake"
+  VERBATIM
+)
 
 if (${MSVC})
   # using Visual Studio C++
@@ -269,6 +282,6 @@ install(TARGETS ${PROJECT_NAME}
   RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")
 install(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR_AUTOGENERATED}/Bindings DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}")
 
 #########################################################
 option(LIB3MF_TESTS "Switch whether the tests of lib3mf should be build" ON)
 message("LIB3MF_TESTS ... " ${LIB3MF_TESTS})
diff --git a/cmake/VerifyTargetFile.cmake b/cmake/VerifyTargetFile.cmake
new file mode 100644
index 00000000..0df99820
--- /dev/null
+++ b/cmake/VerifyTargetFile.cmake
@@ -0,0 +1,7 @@
+if(NOT DEFINED TARGET_FILE OR TARGET_FILE STREQUAL "")
+  message(FATAL_ERROR "VerifyTargetFile.cmake: TARGET_FILE is not set.")
+endif()
+
+if(NOT EXISTS "${TARGET_FILE}")
+  message(FATAL_ERROR "VerifyTargetFile.cmake: built target file not found: ${TARGET_FILE}")
+endif()
diff --git a/lib3mf.pc.in b/lib3mf.pc.in
index bb8030ab..b67375c0 100644
--- a/lib3mf.pc.in
+++ b/lib3mf.pc.in
@@ -8,5 +8,6 @@ Description: @PROJECT_DESCRIPTION@
 Version: @PROJECT_VERSION@
 
 Requires:
-Libs: -L${libdir} -l3mf -lzip -lz
+Libs: -L${libdir} -l3mf
+Libs.private: -lzip -lz
-Cflags: -I${includedir}
+Cflags: -I${includedir}/Bindings/C
