# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokenz < Formula
  desc "Store tokens in Apple Keychain for easy access in Terminal"
  homepage "https://github.com/willswire/tokenz"
  version "0.0.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/willswire/tokenz/archive/refs/tags/v0.0.1.tar.gz"
    sha256 "61f5ce2bea9dda1559cbd2062ed858ffa7fcc582a86257b7c554559e9f048a45"

    def install
      bin.install "tokenz"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/willswire/tokenz/archive/refs/tags/v0.0.1.tar.gz"
    sha256 "8c0408cd38f614539b0f1aa892df93e783387903c4f6b5ff360862468ec50eeb"

    def install
      bin.install "tokenz"
    end
  end
end
