# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokenz < Formula
  desc "Store tokens in Apple Keychain for easy access in Terminal"
  homepage "https://github.com/willswire/tokenz"
  version "0.0.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/willswire/tokenz/archive/refs/tags/#{version}.tar.gz"
    sha256 "64c32431ed21dd5b6d783ec01d3a9e465aa8664c4b6fa493d4f11b96cb0e4504"

    def install
      bin.install "tokenz"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/willswire/tokenz/archive/refs/tags/#{version}.tar.gz"
    sha256 "cc386fbc1babda464c7bd55548e462aa3f090124b56e1b682c4e30cfefb69707"

    def install
      bin.install "tokenz"
    end
  end
end
