# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokenz < Formula
  desc "store tokens in Apple Keychain for easy access in Terminal"
  homepage "https://github.com/willswire/tokenz"
  version "0.0.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/willswire/tokenz/releases/download/v0.0.1/tokenz_Darwin_x86_64.tar.gz"
    sha256 "e07b0f7f45819c9ed388dd704c0079477e618fbc35dc51d6e88b3b642f3c2c1c"

    def install
      bin.install "tokenz"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/willswire/tokenz/releases/download/v0.0.1/tokenz_Darwin_arm64.tar.gz"
    sha256 "830c805201144ddcb1743ca7053af5684f0a72e7fb5ae38a9b11340ddf900482"

    def install
      bin.install "tokenz"
    end
  end
end
