name: Bump formulae on schedule or request

on:
  workflow_dispatch:
    inputs:
      formulae:
        description: Custom list of formulae to livecheck and bump if outdated
        required: false
  schedule:
    # Every day at 5am
    - cron: '0 5 * * *'

env:
  HOMEBREW_FORCE_HOMEBREW_ON_LINUX: 1
  FORMULAE: |
    ack
    activemq
    alda
    allure
    alluxio
    ammonite-repl
    angular-cli
    ant
    ant@1.9
    apache-archiva
    apache-drill
    apache-flink
    apache-geode
    apache-opennlp
    apache-spark
    apidoc
    apktool
    argo
    argocd
    argocd-autopilot
    argocd-vault-plugin
    armadillo
    artifactory
    asciidoctorj
    asymptote
    atuin
    autorest
    avrdude
    aws-cdk
    b3sum
    baidupcs-go
    ballerina
    bash_unit
    batik
    bazel
    bazelisk
    bbtools
    bcoin
    bear
    bee
    bigloo
    bnd
    bottom
    brew-php-switcher
    broot
    buildifier
    buildkit
    buildozer
    bundletool
    byacc
    byteman
    cadence
    calicoctl
    cargo-audit
    cargo-bloat
    cargo-c
    cargo-edit
    cargo-instruments
    cargo-llvm-lines
    cargo-outdated
    cargo-watch
    carrot2
    cassandra
    cassandra-reaper
    catch2
    cdk8s
    cfr-decompiler
    checkstyle
    chezmoi
    chromaprint
    circleci
    clair
    clash
    cliclick
    clojurescript
    closure-compiler
    cloudflare-wrangler
    code-minimap
    coinutils
    composer
    consul
    consul-template
    couchdb
    cromwell
    crowdin
    crun
    css-crush
    cubejs-cli
    cypher-shell
    dafny
    datree
    davmail
    deark
    deno
    dependency-check
    derby
    detekt
    detox
    devspace
    dex2jar
    digdag
    django-completion
    djl-serving
    dnscrypt-proxy
    docker
    docker-compose
    docker-slim
    doctl
    docuum
    double-conversion
    dprint
    druid
    dtm
    dvc
    easyengine
    efm-langserver
    elasticsearch@6
    emscripten
    envconsul
    esbuild
    eslint
    etcd
    ethereum
    exploitdb
    fabric-installer
    fantom
    faudio
    feh
    fennel
    firebase-cli
    flank
    flarectl
    flume
    flux
    flyway
    fmt
    fop
    ford
    fuse-overlayfs
    fuseki
    futhark
    futhark
    gatsby-cli
    ginac
    git-annex
    git-cliff
    git-delta
    gitbackup
    gitbucket
    gitleaks
    glassfish
    gleam
    glooctl
    gmsh
    gnunet
    gnupg-pkcs11-scd
    gnuplot
    gofish
    golang-migrate
    google-java-format
    goreleaser
    gosec
    gostatic
    gpg-tui
    gradle
    gradle-completion
    gradle-profiler
    grails
    groovy
    groovysdk
    hadoop
    halide
    hapi-fhir-cli
    hcloud
    helm
    helmfile
    hidapi
    hive
    htmldoc
    htmlq
    htpdate
    hugo
    igv
    imagemagick
    imagemagick@6
    imap-backup
    ipmiutil
    ipopt
    ircd-hybrid
    ivy
    jadx
    java-service-wrapper
    jena
    jenkins
    jenkins-job-builder
    jenkins-lts
    jetty
    jetty-runner
    jfrog-cli
    jhipster
    jmeter
    jnethack
    jql
    jruby
    jsonnet
    jsonschema
    jsvc
    just
    k3d
    k9s
    kafka
    kalker
    keptn
    keydb
    ki
    kitchen-sync
    knot
    knot-resolver
    kotlin
    ktlint
    kubeaudit
    kubecfg
    kumactl
    kustomize
    languagetool
    latex2html
    latexml
    lazydocker
    leiningen
    lexbor
    libdap
    libgetdata
    libgr
    liboqs
    libpano
    libpipeline
    librdkafka
    liquibase
    lmod
    localstack
    log4cxx
    lout
    macchina
    mailutils
    marked
    marp-cli
    maven
    mavsdk
    maxwell
    mdbook
    mdcat
    mdzk
    meson
    metabase
    micro
    micronaut
    mill
    minikube
    mmctl
    moco
    moto
    mpv
    murex
    mypy
    nanoflann
    nativefier
    navi
    ncc
    neo4j
    neofetch
    netlify-cli
    nexus
    nfpm
    nng
    node-sass
    nomad
    notcurses
    nushell
    oauth2_proxy
    oci-cli
    octant
    octave
    okteto
    onedrive
    opensearch
    orc-tools
    orientdb
    ortp
    oxipng
    pacapt
    payara
    pdftk-java
    pgloader
    phoronix-test-suite
    php-code-sniffer
    php-cs-fixer
    phpmd
    phpstan
    picard-tools
    pickle
    pig
    pillow
    plantuml
    pmd
    pnpm
    pocsuite3
    presto
    procs
    protoc-gen-go-grpc
    psalm
    qpid-proton
    questdb
    rbw
    rebar3
    regina-rexx
    reminiscence
    riemann
    rollup
    rqlite
    rubberband
    s2n
    sbt
    scala
    scotch
    scummvm
    scummvm-tools
    sdl2
    seaweedfs
    selene
    selenium-server
    seqkit
    ser2net
    serverless
    sjk
    skaffold
    skopeo
    sleuthkit
    solana
    solr
    solr@7.7
    sonarqube
    sonarqube-lts
    sponge
    spotbugs
    sqlmap
    stanford-corenlp
    starship
    stdman
    storm
    stress-ng
    structurizr-cli
    subversion
    svgo
    svtplay-dl
    swagger-codegen
    swagger-codegen@2
    syncthing
    tcsh
    tealdeer
    teleport
    termshark
    terraform-ls
    thrift
    tika
    toast
    tomcat
    tomcat-native
    tomcat@8
    tomcat@9
    tomee-plume
    tomee-plus
    tomee-webprofile
    topgrade
    traefik
    trafficserver
    trino
    typedb
    universal-ctags
    vale
    vault-cli
    vercel-cli
    virgil
    vite
    vpn-slice
    vsearch
    vue-cli
    wakatime-cli
    wasmtime
    webpack
    webtorrent-cli
    whistle
    whois
    wildfly-as
    wiremock-standalone
    wolfssl
    xalan-c
    xcbeautify
    xerces-c
    xgboost
    xplr
    yaegi
    zbctl
    zellij
    zookeeper

jobs:
  autobump:
    if: github.repository == 'Homebrew/homebrew-core'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu16.04:master
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'BrewTestBot' }}

      - name: Bump formulae
        uses: Homebrew/actions/bump-formulae@master
        continue-on-error: true
        with:
          token: ${{ secrets.HOMEBREW_CORE_REPO_WORKFLOW_TOKEN }}
          formulae: ${{ github.event.inputs.formulae || env.FORMULAE }}
