name: Bump formulae on schedule or request

on:
  workflow_dispatch:
    inputs:
      formulae:
        description: Custom list of formulae to livecheck and bump if outdated
        required: false
  schedule:
    # Every day at 5am
    - cron: '0 5 * * *'

env:
  HOMEBREW_FORCE_HOMEBREW_ON_LINUX: 1
  FORMULAE: |
    ack
    activemq
    alda
    allure
    alluxio
    ammonite-repl
    angular-cli
    ant
    apache-archiva
    apache-flink
    apache-opennlp
    apidoc
    apktool
    argo
    artifactory
    asciidoctorj
    atuin
    autorest
    aws-cdk
    b3sum
    ballerina
    bazel
    bazelisk
    bbtools
    bcoin
    bee
    bnd
    bottom
    brew-php-switcher
    broot
    buildifier
    buildkit
    buildozer
    bundletool
    byteman
    cadence
    calicoctl
    cargo-audit
    cargo-bloat
    cargo-c
    cargo-edit
    cargo-instruments
    cargo-llvm-lines
    cargo-outdated
    cargo-watch
    carrot2
    cassandra
    cassandra-reaper
    cdk8s
    cfr-decompiler
    checkstyle
    chezmoi
    chromaprint
    circleci
    clair
    cliclick
    clojurescript
    closure-compiler
    cloudflare-wrangler
    composer
    consul
    consul-template
    cromwell
    crowdin
    crun
    cubejs-cli
    cypher-shell
    dafny
    davmail
    deno
    dependency-check
    detekt
    detox
    devspace
    dex2jar
    digdag
    djl-serving
    dnscrypt-proxy
    docker
    docker-compose
    docker-slim
    doctl
    docuum
    double-conversion
    dprint
    druid
    dvc
    easyengine
    elasticsearch@6
    emscripten
    envconsul
    esbuild
    eslint
    etcd
    ethereum
    exploitdb
    fabric-installer
    fantom
    fennel
    firebase-cli
    flank
    flarectl
    flux
    flyway
    fuse-overlayfs
    fuseki
    futhark
    gatsby-cli
    git-cliff
    git-delta
    gitbucket
    gitleaks
    glassfish
    gleam
    glooctl
    gofish
    golang-migrate
    google-java-format
    goreleaser
    gosec
    gostatic
    gpg-tui
    gradle
    gradle-completion
    gradle-profiler
    grails
    groovy
    groovysdk
    hapi-fhir-cli
    hcloud
    helm
    helmfile
    htmldoc
    hugo
    igv
    imagemagick
    imagemagick@6
    imap-backup
    ipopt
    ircd-hybrid
    jadx
    java-service-wrapper
    jena
    jenkins
    jenkins-lts
    jetty
    jetty-runner
    jfrog-cli
    jhipster
    jmeter
    jql
    jruby
    jsonnet
    just
    k3d
    k9s
    kafka
    keptn
    keydb
    ki
    kotlin
    ktlint
    kubeaudit
    kubecfg
    kumactl
    kustomize
    languagetool
    lazydocker
    leiningen
    lexbor
    liboqs
    librdkafka
    liquibase
    localstack
    lout
    macchina
    marked
    marp-cli
    maven
    maxwell
    mdbook
    mdcat
    meson
    metabase
    micro
    micronaut
    mill
    minikube
    mmctl
    moto
    murex
    mypy
    nativefier
    navi
    ncc
    neo4j
    neofetch
    netlify-cli
    nexus
    nfpm
    nng
    node-sass
    nomad
    notcurses
    nushell
    oauth2_proxy
    oci-cli
    octant
    octave
    okteto
    opensearch
    orc-tools
    orientdb
    oxipng
    payara
    pdftk-java
    phoronix-test-suite
    php-code-sniffer
    php-cs-fixer
    phpmd
    phpstan
    picard-tools
    pickle
    plantuml
    pmd
    pnpm
    pocsuite3
    presto
    procs
    protoc-gen-go-grpc
    psalm
    questdb
    rbw
    riemann
    rollup
    rubberband
    s2n
    sbt
    scala
    selene
    selenium-server
    serverless
    sjk
    skaffold
    skopeo
    sleuthkit
    solana
    solr
    sonarqube
    sonarqube-lts
    sponge
    spotbugs
    stanford-corenlp
    starship
    stdman
    storm
    stress-ng
    structurizr-cli
    svgo
    svtplay-dl
    swagger-codegen
    swagger-codegen@2
    syncthing
    teleport
    termshark
    terraform-ls
    tika
    toast
    tomcat
    tomcat-native
    tomcat@8
    tomcat@9
    topgrade
    traefik
    trino
    typedb
    vale
    vault-cli
    vercel-cli
    virgil
    vite
    vpn-slice
    vsearch
    vue-cli
    wasmtime
    webpack
    webtorrent-cli
    whistle
    wildfly-as
    wiremock-standalone
    xcbeautify
    xgboost
    xplr
    yaegi
    zellij

jobs:
  autobump:
    if: github.repository == 'Homebrew/homebrew-core'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu16.04:master
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@master
        with:
          username: ${{ (github.event_name == 'workflow_dispatch' && github.actor) || 'BrewTestBot' }}

      - name: Bump formulae
        uses: Homebrew/actions/bump-formulae@master
        continue-on-error: true
        with:
          token: ${{ secrets.HOMEBREW_CORE_REPO_WORKFLOW_TOKEN }}
          formulae: ${{ github.event.inputs.formulae || env.FORMULAE }}
