name: Cache

on:
  push:
    paths:
      - .github/workflows/cache.yml
  schedule:
    - cron: "0 */6 * * *" # every 6 hours

concurrency:
  group: cache
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  update:
    if: github.repository_owner == 'Homebrew'
    strategy:
      matrix:
        runner:
          - macos-11
          - macos-12
          - macos-13
          - ubuntu-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Cache Homebrew Gems
        uses: Homebrew/actions/populate-gems-cache@master
