name: Generate formulae.brew.sh

on:
  push:
    branches:
      - master

jobs:
  generate:
    if: github.repository == 'Homebrew/homebrew-core'
    runs-on: macos-latest
    env:
      HOMEBREW_COLOR: 1
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - name: Set up git-ssh
        uses: Homebrew/actions/git-ssh@master
        with:
          git_user: BrewTestBot
          git_email: homebrew-test-bot@lists.sfconservancy.org
          key: ${{ secrets.FORMULAE_DEPLOY_KEY }}

      - name: Set up Homebrew
        run: |
          brew update-reset $(brew --repository)
          brew tap ${{ github.repository }}
          brew update-reset $(brew --repository ${{ github.repository }})
          echo ${{ secrets.ANALYTICS_JSON_KEY }} > ~/.homebrew_analytics.json

      - name: Build and push formulae.brew.sh
        run: |
          # clone formulae.brew.sh with SSH so we can push back
          git clone --depth=1 --quiet git@github.com:Homebrew/formulae.brew.sh
          cd formulae.brew.sh

          # run Rakefile
          /usr/bin/rake

          # commit and push generated files
          git add _data/formula api/formula formula

          if ! git diff --exit-code HEAD -- _data/analytics _data/formula api/formula formula cask; then
            git commit -m "formula: update from ${{ github.repository }} push" _data/analytics _data/formula api/formula formula
            git fetch
            git rebase origin/master
            git push
          fi
