name: Publish and commit bottles

run-name: "Publish PR #${{ inputs.pull_request }}"

on:
  workflow_dispatch:
    inputs:
      pull_request:
        description: Pull request number
        required: true
      large_runner:
        description: "Run the upload job on a large runner? (default: false)"
        type: boolean
        required: false
        default: false
      autosquash:
        description: "Squash pull request commits according to Homebrew style? (default: false)"
        type: boolean
        required: false
        default: false
      warn_on_upload_failure:
        description: "Pass `--warn-on-upload-failure` to `brew pr-pull`? (default: false)"
        type: boolean
        required: false
        default: false
      message:
        description: "Message to include when autosquashing revision bumps, deletions, and rebuilds (requires autosquash)"
        required: false

env:
  GNUPGHOME: /tmp/gnupghome
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1
  GH_REPO: ${{github.repository}}
  GH_NO_UPDATE_NOTIFIER: 1
  GH_PROMPT_DISABLED: 1
  RUN_URL: ${{github.event.repository.html_url}}/actions/runs/${{github.run_id}}

permissions:
  contents: read

jobs:
  upload:
    runs-on: ${{inputs.large_runner && 'homebrew-large-bottle-upload' || 'ubuntu-22.04'}}
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master
    permissions:
      pull-requests: write
    steps:
      - name: Post comment once started
        uses: Homebrew/actions/post-comment@master
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          issue: ${{github.event.inputs.pull_request}}
          body: ":shipit: @${{github.actor}} has [requested bottles to be published to this PR](${{env.RUN_URL}})."
          bot_body: ":robot: A scheduled task has [requested bottles to be published to this PR](${{env.RUN_URL}})."
          bot: BrewTestBot

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Configure Git user
        id: git-user-config
        uses: Homebrew/actions/git-user-config@master
        with:
          username: BrewTestBot

      - name: Set up commit signing
        uses: Homebrew/actions/setup-commit-signing@master
        with:
          signing_key: ${{ secrets.BREWTESTBOT_GPG_SIGNING_SUBKEY }}

      - name: Checkout PR branch
        run: gh pr checkout '${{github.event.inputs.pull_request}}'
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        working-directory: ${{steps.set-up-homebrew.outputs.repository-path}}

      - name: Pull and upload bottles to GitHub Packages
        env:
          BREWTESTBOT_NAME_EMAIL: "${{ steps.git-user-config.outputs.name }} <${{ steps.git-user-config.outputs.email }}>"
          HOMEBREW_GPG_PASSPHRASE: ${{ secrets.BREWTESTBOT_GPG_SIGNING_SUBKEY_PASSPHRASE }}
          HOMEBREW_GITHUB_API_TOKEN: ${{secrets.HOMEBREW_CORE_PUBLIC_REPO_EMAIL_TOKEN}}
          HOMEBREW_GITHUB_PACKAGES_USER: brewtestbot
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{secrets.HOMEBREW_CORE_GITHUB_PACKAGES_TOKEN}}
        run: |
          # Don't quote arguments that might be empty; this causes errors.
          brew pr-pull \
            --debug \
            --no-cherry-pick \
            --workflows=tests.yml \
            --committer="$BREWTESTBOT_NAME_EMAIL" \
            --root-url="https://ghcr.io/v2/homebrew/core" \
            '${{inputs.autosquash && '--autosquash' || '--clean'}}' \
            ${{inputs.warn_on_upload_failure && '--warn-on-upload-failure' || ''}} \
            ${{inputs.message && format('--message="{0}"', inputs.message) || ''}} \
            '${{github.event.inputs.pull_request}}'

      - name: Get current branch and remote
        id: push-configuration
        working-directory: ${{steps.set-up-homebrew.outputs.repository-path}}
        run: |
          branch="$(git branch --show-current)"
          if [ -n "$branch" ]
          then
            echo "branch=$branch" >> "$GITHUB_OUTPUT"
          else
            echo "::error ::Not on a branch!"
            exit 1
          fi

          if push_remote="$(git config --local "branch.$branch.pushRemote")"
          then
            echo "remote=$push_remote" >> "$GITHUB_OUTPUT"
          elif remote="$(git config --local "branch.$branch.remote")"
          then
            echo "remote=$remote" >> "$GITHUB_OUTPUT"
          else
            echo "::error ::Could not find branch remote!"
            exit 1
          fi

      - name: Push commits
        id: push
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN}}
          directory: ${{steps.set-up-homebrew.outputs.repository-path}}
          remote: ${{steps.push-configuration.outputs.remote}}
          branch: ${{steps.push-configuration.outputs.branch}}
          force: ${{inputs.autosquash}}
          no_lease: ${{inputs.autosquash}}
          tries: ${{inputs.autosquash && '1' || '5'}}
        env:
          GIT_COMMITTER_NAME: ${{ steps.git-user-config.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.git-user-config.outputs.email }}
          HOMEBREW_GPG_PASSPHRASE: ${{ secrets.BREWTESTBOT_GPG_SIGNING_SUBKEY_PASSPHRASE }}

      - name: Add CI-published-bottle-commits label
        run: gh pr edit --add-label CI-published-bottle-commits '${{github.event.inputs.pull_request}}'
        working-directory: ${{steps.set-up-homebrew.outputs.repository-path}}
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Post comment on failure
        if: ${{!success()}}
        uses: Homebrew/actions/post-comment@master
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          issue: ${{github.event.inputs.pull_request}}
          body: ":warning: @${{github.actor}} bottle publish [failed](${{env.RUN_URL}})."
          bot_body: ":warning: Bottle publish [failed](${{env.RUN_URL}})."
          bot: BrewTestBot

      - name: Dismiss approvals on failure
        if: ${{!success()}}
        uses: Homebrew/actions/dismiss-approvals@master
        with:
          token: ${{secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN}}
          pr: ${{github.event.inputs.pull_request}}
          message: "bottle publish failed"

      - name: Wait until pull request branch is in sync with local repository
        working-directory: ${{steps.set-up-homebrew.outputs.repository-path}}
        run: |
          local_head="$(git rev-parse HEAD)"
          echo "::notice ::Local repository HEAD: $local_head"

          attempt=0
          max_attempts=10
          timeout=1

          # Wait (with exponential backoff) until the PR branch is in sync
          while [ "$attempt" -lt "$max_attempts" ]
          do
            remote_head="$(git ls-remote origin "pull/${{inputs.pull_request}}/head" | cut -f1)"
            echo "::notice ::Pull request HEAD: $remote_head"
            if [ "$local_head" = "$remote_head" ]
            then
              success=1
              break
            fi
            echo "::notice ::Remote repository not in sync. Checking again in ${timeout}s..."
            sleep "$timeout"
            attempt=$(( attempt + 1 ))
            timeout=$(( timeout * 2 ))
          done

          # One last check...
          if [ -z "$success" ] && [ "$local_head" != "$(git ls-remote origin "pull/${{inputs.pull_request}}/head" | cut -f1)" ]
          then
            echo "::error ::No attempts remaining. Giving up."
            exit 1
          fi

      - name: Enable PR automerge
        id: automerge
        env:
          GH_TOKEN: ${{secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN}}
        working-directory: ${{steps.set-up-homebrew.outputs.repository-path}}
        run: gh pr merge --auto --merge '${{inputs.pull_request}}'

      - name: Post comment on failure
        if: ${{failure() && steps.automerge.conclusion == 'failure'}}
        uses: Homebrew/actions/post-comment@master
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          issue: ${{github.event.inputs.pull_request}}
          body: ":warning: @${{github.actor}} [Failed to enable automerge](${{env.RUN_URL}})."
          bot_body: ":warning: [Failed to enable automerge](${{env.RUN_URL}})."
          bot: BrewTestBot

      - name: Rebase on origin/master for fallback
        if: failure() && steps.push.conclusion == 'failure'
        working-directory: ${{steps.set-up-homebrew.outputs.repository-path}}
        run: |
          git fetch origin
          git rebase origin/master || git rebase --abort

      - name: Push commits (fallback)
        id: push-fallback
        if: failure() && steps.push.conclusion == 'failure'
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN}}
          directory: ${{steps.set-up-homebrew.outputs.repository-path}}
          branch: ${{steps.push-configuration.outputs.branch}}
          tries: '5'
        env:
          GIT_COMMITTER_NAME: ${{ steps.git-user-config.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.git-user-config.outputs.email }}
          HOMEBREW_GPG_PASSPHRASE: ${{ secrets.BREWTESTBOT_GPG_SIGNING_SUBKEY_PASSPHRASE }}

      - name: Open separate PR with bottle commits after push failure
        id: fallback-pr
        if: failure() && steps.push-fallback.conclusion == 'success'
        working-directory: ${{steps.set-up-homebrew.outputs.repository-path}}
        env:
          GH_TOKEN: ${{secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN}}
        run: |
          name='${{github.workflow}}'
          url='${{github.server_url}}/${{github.workflow_ref}}'
          branch='${{steps.push-configuration.outputs.branch}}'

          echo "Created by [$name][$url] after [failed push]($RUN_URL)." > pr_body
          echo >> pr_body
          echo 'Closes #${{inputs.pull_request}}' >> pr_body

          gh pr create \
            --base master \
            --body-file pr_body \
            --head "$branch" \
            --label CI-published-bottle-commits \
            --title 'Recreation of #${{inputs.pull_request}}'

          pull_number="$(gh pr list --head "$branch" | cut -f1 | tr -d '\n')"
          gh pr merge --auto --merge "$pull_number"
          echo "pull_number=$pull_number" >> "$GITHUB_OUTPUT"

      - name: Enable automerge on fallback PR
        id: replacement-pr
        if: failure() && steps.fallback-pr.conclusion == 'success'
        working-directory: ${{steps.set-up-homebrew.outputs.repository-path}}
        env:
          GH_TOKEN: ${{secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN}}
        run: |
          pull_number="$(gh pr list --head "$branch" | cut -f1 | tr -d '\n')"
          gh pr merge --auto --merge "$pull_number"
          echo "pull_number=$pull_number" >> "$GITHUB_OUTPUT"

      - name: Post comment for fallback PR
        if: failure() && steps.fallback-pr.conclusion == 'success'
        uses: Homebrew/actions/post-comment@master
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          issue: ${{github.event.inputs.pull_request}}
          body: ":ship: @${{github.actor}} Replacement PR opened at #${{steps.replacement-pr.outputs.pull_number}}."
          bot_body: ":ship: Replacement PR opened at #${{steps.fallback-pr.outputs.pull_number}}."
          bot: BrewTestBot

      - name: Post comment on fallback creation
        if: >
          failure() &&
          (steps.push-fallback.conclusion == 'failure' || steps.fallback-pr.conclusion == 'failure')
        uses: Homebrew/actions/post-comment@master
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          issue: ${{github.event.inputs.pull_request}}
          body: ":warning: @${{github.actor}} [Failed to create replacement PR](${{env.RUN_URL}})."
          bot_body: ":warning: [Failed to create replacement PR](${{env.RUN_URL}})."
          bot: BrewTestBot
