name: Recreate Linux self-hosted runners on schedule

on:
  workflow_dispatch:
  schedule:
    # Once each 24 hours, at 1 during the night
    - cron: "0 1 * * *"

concurrency:
  group: recreate-linux-runners
  cancel-in-progress: true

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  recreate:
    if: github.repository == 'Homebrew/homebrew-core'
    runs-on: ubuntu-22.04
    env:
      # TODO agree on one label for all runners
      RUNNER_LABEL: TODO
    strategy:
      matrix:
        runner_name:
          - linux-self-hosted-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      
      - name: Authenticate to Google Cloud
        id: 'gcloud-auth'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: access_token
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUM }}/locations/global/workloadIdentityPools/recreate-linux-runners/providers/github-provider
          service_account: recreate-linux-runners@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Wait for idle runner
        id: killable
        uses: Homebrew/actions/wait-for-idle-runner@master
        with:
          runner_name: ${{ matrix.runner_name }}
          github_token: ${{ secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN }}

      - name: Kill runner and create a new one
        if: ${{ steps.killable.outputs.runner-found == 'true' && steps.killable.outputs.runner-idle == 'true' }}
        uses: Homebrew/actions/create-gcloud-instance@master
        with:
          runner_name: ${{ matrix.runner_name }}
          gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
          github_token: ${{ secrets.HOMEBREW_GITHUB_PUBLIC_REPO_TOKEN }}
