name: "Close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GH_ACTION_STALE_KEY }}
        stale-issue-message: >
          This issue is stale because it has been open 30 days with no activity.
          Remove stale label or comment or this will be closed in 5 days
        days-before-stale: >
          This issue has been automatically marked as stale because it has not had
          recent activity. It will be closed if no further activity occurs. Thank you
          for your contributions.
        days-before-stale: 30
        days-before-close: 5
